#!/usr/bin/env bash

# will not stretch image-- too laggy
LOCKSCREEN=~/wallpaper/lockscreen.png
BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#303246E6'
TEXT='#303246E6'
WRONG='#b20000ff'
PRESS='#acb231e6'
VERIFYING='#00564dE6'

i3lock                            \
    --insidever-color=$BLANK      \
    --ringver-color=$VERIFYING    \
                                  \
    --insidewrong-color=$BLANK    \
    --ringwrong-color=$WRONG      \
                                  \
    --inside-color=$BLANK         \
    --ring-color=$DEFAULT         \
    --line-color=$BLANK           \
    --separator-color=$DEFAULT    \
                                  \
    --verif-color=$TEXT           \
    --wrong-color=$TEXT           \
    --time-color=$TEXT            \
    --date-color=$TEXT            \
    --layout-color=$TEXT          \
    --keyhl-color=$PRESS          \
    --bshl-color=$WRONG           \
                                  \
    --ignore-empty-password       \
    --nofork                      \
    -i $LOCKSCREEN                \
    --indicator                   \
    --ring-width=5                \
    --radius=100                  \
    --verif-text=""               \
    --lock-text=""                \
    --wrong-text=""               \
    --noinput-text=""             \
    --force-clock                 \
    --time-str="%H:%M:%S"         \
    --time-size=80                \
    --time-pos="ix:300"           \
    --date-str="%d. %h %Y"        \
    --date-size=60                \
    --date-pos="ix:ty+80"         \
    --keylayout 0                 \
    --layout-size=30              \
    --layout-pos="ix:iy+15"
