[env]
TERM = "xterm-256color"

[font]
size = 12.0

# [font.bold]
# family = "Mononoki Nerd Font"
# style = "Bold"
#
# [font.bold_italic]
# family = "Mononoki Nerd Font"
# style = "Bold Italic"
#
# [font.italic]
# family = "Mononoki Nerd Font"
# style = "Italic"
#
# [font.normal]
# family = "Monego Nerd Font Fix"
# style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 5000

[window]
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
